### ISSUE TITLE
Does fuzzercorn work with qiling framework?

### ISSUE THREAD

**Issue by dzonerzy** [wtdcode/fuzzercorn#1]
As the title state , I wanted  to know if fuzzercorn works with qiling

**Comment by wtdcode** [comment]
Of course it does.

https://github.com/qilingframework/qiling/blob/dev/examples/fuzzing/linux_x8664/libfuzzer_x8664_linux.py

**Comment by dzonerzy** [comment]
Oh nice missed that, support is only for x86_64 or arm too?

**Comment by wtdcode** [comment]
> Oh nice missed that, support is only for x86_64 or arm too?

I suppose it should support arm but I haven't tested it yet.

**Comment by dzonerzy** [comment]
Tested and working, awesome work!
